apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-helloworld 
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: aks-helloworld
  template:
    metadata:
      labels:
        app: aks-helloworld
    spec:
      containers:
        - name: aks-helloworld
          image: ghcr.io/hashilbasheer/react-poc:{{ .Values.image.tag }}
          ports:
          - containerPort: 3000
